// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Utiliser l'URL Neon non-pooled ici pour les migrations (voir .env.example)
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
